### ISSUE TITLE
Building shapes split in two by parcel, city or some other boundaries

### ISSUE THREAD

**Issue by jschleuss** [osmlab/labuildings#71] opened 2016-04-04 21:42 UTC
I usually find at least one or two in each block group. It appears to be a problem with the source data from LARIAC, so not much we can do to fix it at the start. I've recommended using "Join overlapping Areas" to combine them. 

![screen shot 2016-04-04 at 2 38 36 pm](https://cloud.githubusercontent.com/assets/695934/14264162/74ab59f4-fa73-11e5-8c4e-896c7fa2c2e4.png)
If it's a small sliver, it makes sense that the "proper" data is on the larger object. Then I delete all the tags with the sliver and join. If it's larger, like a strip mall split into pieces I think this could be appropriate:
- lacounty:ain -> ALL
- lacount:bld_id -> ALL
- start_date -> None if multiple or the one option if there's only one
- height -> largest number
- ele -> largest number 
- building:units -> none if different
![screen shot 2016-04-04 at 2 38 44 pm](https://cloud.githubusercontent.com/assets/695934/14264157/6c9f23ee-fa73-11e5-8744-e49d7e179003.png)

**Comment by maning** [comment] 2016-04-06 13:28
> source data from LARIAC
Most likely [yes](https://github.com/osmlab/labuildings/issues/3#issuecomment-183159789).

> acounty:ain -> ALL
> lacount:bld_id -> ALL

Why not get the the ID and AIN for the biggest building? Per @tallguy's explanation above this is clearly an artefact of the Assesors processing of parcels and buildings.

**Comment by maning** [comment] 2016-04-11 12:03
@jschleuss Added your notes in the importing guide: https://github.com/osmlab/labuildings/blob/master/IMPORTING.md#validate-the-import-with-your-eyes-before-uploading

**Comment by almccon** [comment] 2016-04-11 21:52
Here's another sliver that @imagico noticed (via the mailing list) https://www.openstreetmap.org/way/407792910

He suggests we try to find a way to detect very narrow geometries. @maning I wonder if we could do some kind of analysis using Mapbox OSM QA tiles to identify narrow geometries for review?

**Comment by meetar** [comment] 2016-04-13 15:21
I'm seeing quite a few similar cases with a "sliver" attached to one building, but with many tags shared with the next building over. For instance:

<img width="494" alt="screen shot 2016-04-13 at 11 09 45 am" src="https://cloud.githubusercontent.com/assets/459970/14498436/6f079f52-0168-11e6-8e20-28745b7a305d.png">

In this case, the highlighted sliver shares an `lacounty:ain` and `start_date` with the building to the north, and an `elevation` and `height` shared with (or closer to) the building to the attached building to the south, and a unique `lacounty:bld_id`. This does seem to me to be "an artifact of the Assessors processing of parcels and buildings" as @maning suggested earlier (perhaps owing to some kind of bounding box clipping process), and using "all" as the combination mode for the `ain` data wouldn't be appropriate.

In such cases, would it be better to simply delete the sliver and extend the outline of the attached building instead, if necessary? Or is it important to keep the separate `bld_id`, `height`, and `elevation`, and copy the `ain` and `start_date` properties from the attached building?

**Comment by meetar** [comment] 2016-04-13 15:25
I just found #19 which answered my question :D

Thanks!

**Comment by cityhubla** [comment] 2016-04-15 23:26
@maning, @meetar  these buildings are cut by the property lines of the assessor, but this was done during the [LARIAC](http://egis3.lacounty.gov/dataportal/lariac/) mapping process. It also seems LA City is using it as such, maybe they're not aware. I highlighted the slivers from the City's Building and Safety website.

![image](https://cloud.githubusercontent.com/assets/6407796/14577243/32e9915a-0326-11e6-96d3-f381c2f4a8dd.png)


I did a check what maning has analyzed on gitter chat, showing la county assessor parcels with the 2014 LACITY LARIAC data, you can see that the buildings are not in their respective properties. This would probably show up throughout the county.

![image](https://cloud.githubusercontent.com/assets/6407796/14577249/603475a8-0326-11e6-84bc-6a23bf27c7e5.png)


Since the import.md guidelines instruct mappers to join the two objects. We should also instruct them to double check if the building is actually over the sat imagery, it may be shifted.

**Comment by jschleuss** [comment] 2016-04-18 02:22
@cityhubla I wonder if this is possibly related to the shift @maning already did to the building locations. They all were off by small amounts, about the size of those slivers. Maybe the county's building file created with that bad shift and then cut against the assessor's parcel file (which is correctly located and not shifted).

**Comment by maning** [comment] 2016-04-28 05:47
We created a merging plugin to combine splitted buildings.  Repo is here: https://github.com/Rub21/auto-tools

**How to use**

* Download the [jar file](https://github.com/Rub21/auto-tools/raw/master/dist/auto_tools.jar)
* Copy to your plugins directory, in Mac: `~/Library/JOSM/plugins`
* Select two adjacent buildings.
* In the Menu, click **Auto Tools > Combine LA buildings**
![howtouse](https://cloud.githubusercontent.com/assets/1152236/14869337/66790fc0-0c98-11e6-8084-66b7b4892bb3.gif)

**For discussion**
One thing I need to verify with the import team is the conflation of the building key. Right now, it adds both tags if its different (i.e. `building=house;commercial`).  Automating this can be difficult and there should be user input to verify.

**Comment by almccon** [comment] 2016-04-28 14:25
Shouldn't we use the building value from the larger of the two pieces?

**Comment by jschleuss** [comment] 2016-04-28 16:31
I agree with @almccon. Most of the time it's a sliver of the building (and not two distinct buildings). I usually drop all the tags for the smaller sliver and then do a join with the larger one. 

@maning I can't get the plugin installed on my Mac. Tried copying to plugins folder, but I don't get the "Auto Tools" menu bar after a restart.

**Comment by maning** [comment] 2016-04-28 16:45
> @maning I can't get the plugin installed on my Mac. Tried copying to
plugins folder, but I don't get the "Auto Tools" menu bar after a restart.

You need to activate the plugin in the Preferences > Plugins.

**Comment by cityhubla** [comment] 2016-04-28 16:50
@jschleuss, the shift wasn't caused by us, as the image from the Building and Safety Dept shows, they have it as well. I redownloaded the shapefile from the data portal, and it shows it as such.

**Comment by jschleuss** [comment] 2016-04-28 16:58
Cool. Installed and it's nice. I think that it'll really be helpful when combining buildings with multiple parts (like large elementary schools, and maybe eventually Pasadena).

@cityhubla yeah, it's the city/county's fault. Maybe we should reach out to them and ask them about it. It's damn frustrating.

**Comment by jschleuss** [comment] 2016-04-28 18:12
I called Mark Greninger at the county and he said that L.A. City wanted to cut their building shapes by the parcel line. That's why we're seeing a lot of those slivers. It shouldn't be that much of a problem in the county because, per the county's contract, ```Features will be cut by parcel lines (eg. downtown core buildings) only at visible fire wall junctions.  Townhouses and contiguous buildings crossing parcel lines will not be cut.```

**Comment by cityhubla** [comment] 2016-04-28 18:20
So we should reach out to LA City and let them know, I'll comment on the data portal and reference it through hackforLA.

**Comment by almccon** [comment] 2016-04-28 19:57
@jschleuss @cityhubla it would be great if we could talk about this as another positive outcome of the import: "we helped the city discover and fix problems in their data, for the benefit of everybody!" That would be good news to share.

**Comment by Rub21** [comment] 2016-04-29 04:47
I fixed the problem with `building` tag , the plugin is taking the  larger building tag. 
![merge](https://cloud.githubusercontent.com/assets/1152236/14908259/afec3d46-0d9a-11e6-9e89-52b4e8935a1e.gif)

**Comment by maning** [comment] 2016-04-29 05:59
@Rub21 I'm getting inconsistent results, see: https://github.com/Rub21/auto-tools/issues/1

**Comment by maning** [comment] 2016-05-03 03:32
@Rub21 I tested to day and it works.  Everyone please test and confirm.

**Comment by maning** [comment] 2016-05-17 19:08
Updated the [comment to include the keyboard shortcut](https://github.com/osmlab/labuildings/issues/71#issuecomment-215315991) . This means to work as expected, next steps is to:

- [ ] Update importing guide to include the auto-tools plugin.

**Comment by maning** [comment] 2016-07-26 09:25
This works, ticketed a cleanup task.  Closing.

**Closed by maning** 2016-07-26 09:25 UTC
